### ISSUE TITLE
Implement transaction query API

### ISSUE THREAD

**Issue by marcgrue** [scalamolecule/molecule#10]

**Comment by analytically** [comment]
This would be interesting!

**Comment by analytically** [comment]
How would this look?

**Comment by marcgrue** [comment]
I don't know yet :) I have done a few transaction-related features, see tests here:
[QueryTour](https://github.com/scalamolecule/molecule/blob/master/examples/src/test/scala/molecule/examples/dayOfDatomic/QueryTour.scala#L160-L196)
[Provenance](https://github.com/scalamolecule/molecule/blob/master/examples/src/test/scala/molecule/examples/dayOfDatomic/Provenance.scala#L14-L51)
[Seattle](https://github.com/scalamolecule/molecule/blob/master/examples/src/test/scala/molecule/examples/seattle/SeattleTests.scala#L346-L379)
.. but I'm thinking of a more transaction-related machinery...

**Comment by marcgrue** [comment]
Some transaction-related APIs are now available:

- [Datom data](https://github.com/scalamolecule/molecule/blob/master/coretests/src/test/scala/molecule/coretests/transaction/DatomData.scala)
- [Tx meta data](https://github.com/scalamolecule/molecule/blob/master/coretests/src/test/scala/molecule/coretests/transaction/TxMetaData.scala)
