### ISSUE TITLE
Documentation points to http://localhost:1313/

### ISSUE THREAD

**Issue by analytically** [scalamolecule/molecule#16]
The navigation is broken, points to http://localhost:1313/.

**Comment by marcgrue** [comment]
Fixed, thanks!

**Comment by analytically** [comment]
Still some links are broken?

**Comment by analytically** [comment]
If you go to http://www.scalamolecule.org/manual/database-setup/ directly, nav doesn't work.

**Comment by marcgrue** [comment]
Okay, some old html directories were hanging around. Have updated the old links I could find and removed the old pages.
