### ISSUE TITLE
Schema folders?

### ISSUE THREAD

**Issue by analytically** [scalamolecule/molecule#17]
`Tell sbt where to find your “schema” folders containing definition files:` -> do you mean folders containing `.edn` files? Perhaps scan the default `src/main/resources` and subdirectories?

http://www.scalamolecule.org/manual/schema/

**Comment by marcgrue** [comment]
Can you have a read again and see if my updates have made things a bit more clear? (Also fixed some links)

**Comment by analytically** [comment]
That helps, thanks! Genius.
