### ISSUE TITLE
Two links not working

### ISSUE THREAD

**Issue by analytically** [scalamolecule/molecule#19]
http://localhost:1313/manual/query/parameterize/
http://localhost:1313/manual/query/relationships/

**Comment by marcgrue** [comment]
The pages are there:
http://www.scalamolecule.org/manual/query/parameterize/
http://www.scalamolecule.org/manual/query/relationships/
... but any link pointing to localhost won't work - where did you find those?

**Comment by analytically** [comment]
Hmm maybe my cache. Sorry.

**Comment by marcgrue** [comment]
No problem - my Hugo pages are smart but sometimes too smart ;-)
