### ISSUE TITLE
Add scalaz repo

### ISSUE THREAD

**Issue by analytically** [scalamolecule/molecule#20]
This needs to be added to the instructions:

`resolvers += "Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"`

**Comment by marcgrue** [comment]
Done in [molecule](https://github.com/scalamolecule/molecule/commit/8bdee2e1f97d926072573d1630512445f18dab11) and [molecule-demo](https://github.com/scalamolecule/molecule-demo/commit/53ca532ee1cb223ccb9a86f89892c68176a57de7).
